"""
Django settings for mi_blog project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path


# ==========================================
# RUTA BASE DEL PROYECTO
# ==========================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================================
# SEGURIDAD
# ==========================================

# Clave secreta de Django.
# Por ahora la dejamos así porque estamos trabajando localmente.
SECRET_KEY = 'django-insecure-^4&=g)cdlf00xsa5vvy@9kb#b$y=^i#wb@ev*4z8ow+54)!vb='


# Mientras trabajamos en nuestra computadora
# dejamos DEBUG en True.
DEBUG = True


# Hosts desde los cuales permitimos acceder al proyecto.
# localhost y 127.0.0.1 sirven para desarrollo local.
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]


# ==========================================
# APLICACIONES INSTALADAS
# ==========================================

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Nuestra aplicación
    'blog',
]


# ==========================================
# MIDDLEWARE
# ==========================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


# ==========================================
# URL PRINCIPAL DEL PROYECTO
# ==========================================

ROOT_URLCONF = 'mi_blog.urls'


# ==========================================
# TEMPLATES
# ==========================================

TEMPLATES = [

    {

        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]


# ==========================================
# WSGI
# ==========================================

WSGI_APPLICATION = 'mi_blog.wsgi.application'


# ==========================================
# BASE DE DATOS
# ==========================================

DATABASES = {

    'default': {

        'ENGINE':
            'django.db.backends.sqlite3',

        'NAME':
            BASE_DIR / 'db.sqlite3',

    }

}


# ==========================================
# VALIDACIÓN DE CONTRASEÑAS
# ==========================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# ==========================================
# IDIOMA Y ZONA HORARIA
# ==========================================

# Ponemos Django en español.
LANGUAGE_CODE = 'es-ar'


# Zona horaria de Argentina.
TIME_ZONE = 'America/Argentina/Buenos_Aires'


USE_I18N = True

USE_TZ = True


# ==========================================
# ARCHIVOS ESTÁTICOS
# CSS - JAVASCRIPT - IMÁGENES
# ==========================================

STATIC_URL = 'static/'


# Carpeta donde Django va a juntar
# todos los archivos estáticos al hacer deploy.
STATIC_ROOT = BASE_DIR / 'staticfiles'